
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:454001124394:android:d74b19cfbc07cf401e4f53",
        # firebase_cli_token: "to be added to github secrets",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "eslammhossam1@gmail.com",
        release_notes: "First Fastlane Firebase Distribution"
  )
  end
end
